### ISSUE TITLE
script doesnt check mysql version

### ISSUE THREAD

**Issue by piotrpog** [pixelandtonic/craft-server-check#12]
Testing script doesnt check mysql version and provides message that server is ready to install craft while it is not.

Recently i ran this script on sever with php 7.2, and it informed me that everything was OK and craft was ready for install.

Then i tried to import mysql database using phpmyadmin, and i got error:
`#1115 - Unknown character set: 'utf8mb4' `

Turns out that mysql installed on server was version `5.1.73-cll`, and craft requires at least `5.5.3`. After changing it to version 5.6 everything installed correctly.

**Comment by angrybrad** [comment]
The requirements checker is checking for a minimum database version (whether it's MySQL or PostgreSQL): https://github.com/craftcms/server-check/blob/master/server/requirements/RequirementsChecker.php#L405-L408

Which is defined here: https://github.com/craftcms/server-check/blob/master/server/requirements/RequirementsChecker.php#L53-L54

And checked here: https://github.com/craftcms/server-check/blob/master/server/requirements/requirements.php#L18-L56

I'm having a hard time reproducing what you're seeing.

`5.1.73-cll` sounds suspiciously like the MySQL client version that is installed instead of the MySQL server version that Craft is checking against, so my best guess is that it's a coincidence and there was something else going on with your issue.
